version: '3.3'

services:

  database:
    build: ./docker/database
    volumes: [ data:/backups/ ]
    ports: [ 3306:3306 ]
    restart: always
    env_file: [ ./docker/config/.env ]
    container_name: nest-application-database

  application:
    build: .
    ports: [ 3000:3000 ]
    restart: always
    depends_on:
      - database
    container_name: nest-application

volumes:

  data: {}
